### GET request to create patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "omen13656",
  "address": "Street 1, LA",
  "email": "omen1324d85@hp.com",
  "dateOfBirth": "1995-03-12",
  "registrationDate": "2024-09-12"
}
###